# Generated by Django 5.1.5 on 2025-01-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_drf_extra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentDrf',
        ),
    ]
